In [27]:
import influxdb_client 

import pandas as pd

token = "mqo_DwUps71AVWT_o5seGC3Y4qSskDO0iUiUjLtgIGj_Up4v1kmADazokM9mRUoNv6I6ryDgv7pgQguGcjB3wQ=="
org = "a.marana@equsdesign.com"
host = "https://eastus-1.azure.cloud2.influxdata.com"
bucket = "cf_arjona"

client = influxdb_client.InfluxDBClient(
    url=host,
    token=token,
    org=org, verify_ssl=False
    )

query_fan = """from(bucket: "cf_arjona")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "prueba")
"""

# Execute the query


query_api = client.query_api()
result = query_api.query_data_frame(org="a.marana@equsdesign.com", query=query_fan.strip())

/Users/franciscoantonioprietorodriguez/Documents/streamlit_iaxxon/.venv/lib/python3.12/site-packages/influxdb_client/client/warnings.py:31: MissingPivotFunction: The query doesn't contains the pivot() function.

The result will not be shaped to optimal processing by pandas.DataFrame. Use the pivot() function by:

    from(bucket: "cf_arjona")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "prueba") |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")

You can disable this warning by:
    import warnings
    from influxdb_client.client.warnings import MissingPivotFunction

    warnings.simplefilter("ignore", MissingPivotFunction)

For more info see:
    - https://docs.influxdata.com/resources/videos/pivots-in-flux/
    - https://docs.influxdata.com/flux/latest/stdlib/universe/pivot/
    - https://docs.influxdata.com/flux/latest/stdlib/influxdata/influxdb/schema/fieldsascols/

  warnings.warn(message, MissingPivotFunction)
/Users/franciscoantonioprietorodriguez/Documents/streamlit_iaxxon/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'eastus-1.azure.cloud2.influxdata.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [28]:
result

,result,table,_start,_stop,_time,_value,_field,_measurement
0,_result,0,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 07:37:27+00:00,15.31,TINT,prueba
1,_result,0,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 07:42:27+00:00,15.38,TINT,prueba
2,_result,0,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 07:47:27+00:00,15.38,TINT,prueba
3,_result,0,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 07:52:27+00:00,15.38,TINT,prueba
4,_result,0,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 07:57:27+00:00,15.38,TINT,prueba
...,...,...,...,...,...,...,...,...
103,_result,8,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 08:12:27+00:00,20.56,TDAC,prueba
104,_result,8,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 08:17:27+00:00,20.56,TDAC,prueba
105,_result,8,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 08:22:27+00:00,20.56,TDAC,prueba
106,_result,8,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 08:27:27+00:00,20.56,TDAC,prueba
107,_result,8,2024-12-15 07:37:24.716707+00:00,2024-12-15 08:37:24.716707+00:00,2024-12-15 08:32:27+00:00,20.56,TDAC,prueba

In [29]:
'main' in ['main','b']

True